Fix renamed `rcpputils` header
ros2/rmw_implementation pull request #198
Opened 2021-11-02 07:29 UTC by aprotyas

`rcpputils/get_env.hpp` is renamed to `rcpputils/env.hpp` as part of https://github.com/ros2/rcpputils/pull/150, so the corresponding includes have been fixed in this PR.

Signed-off-by: Abrar Rahman Protyasha <aprotyas@u.rochester.edu>

2021-11-02 07:38 UTC, aprotyas commented
The Rpr job fails as expected because the renamed header is not in a release yet.

CI from https://github.com/ros2/rcpputils/pull/150:

Repos file: https://gist.github.com/aprotyas/96874af9175859555af0144398e0bf25
Build/Test args: `--packages-above-and-dependencies rcpputils`
ROS distro: Rolling
Job: https://ci.ros2.org/job/ci_launcher/9263

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=15548)](http://ci.ros2.org/job/ci_linux/15548/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=10232)](http://ci.ros2.org/job/ci_linux-aarch64/10232/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=13215)](http://ci.ros2.org/job/ci_osx/13215/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15760)](http://ci.ros2.org/job/ci_windows/15760/)

2021-11-02 12:43 UTC, clalancette requested changes

2021-11-02 12:43 UTC, clalancette commented on rmw_implementation/src/functions.cpp
> +#include "rcpputils/env.hpp"
This isn't right, as far as I can tell.  We deprecated `rcutils/get_env.h`, not `rcpputils/get_env.hpp`.  So I don't think this is going to work.

2021-11-02 12:44 UTC, clalancette commented on rmw_implementation/src/functions.cpp
> +#include "rcpputils/env.hpp"
Oh, never mind me.  I didn't read the whole description, the whole point of this is to add that :).

2021-11-03 18:27 UTC, clalancette approved these changes

2021-11-11 07:20 UTC, aprotyas commented
Two approvals and CI is green, so I'll merge this in. Thanks for the reviews!

2021-11-11 07:20 UTC, merged